language: cpp
compiler:
- g++
install:
- sudo pip install codecov
os:
- linux
script:
- make
- make test
- make gcov
branches:
  only:
  - master
after_success:
  - codecov -t b051e1e4-03e9-4630-8bf9-52237449ed73 -X gcov

